CREATE TABLE T_OPC_SERVER (
ID_OPC NUMBER NOT NULL,
IP_ADDRESS VARCHAR2(16 BYTE),
HOST_NAME VARCHAR2(35 BYTE),
PROG_ID VARCHAR2(50 BYTE),
TAG_SUFFIX VARCHAR2(30 BYTE),
DESCRIPTION VARCHAR2(100 BYTE),
TAG_PREFIX VARCHAR2(20 BYTE),
USERNAME VARCHAR2(15 BYTE),
PASSWORD VARCHAR2(15 BYTE),
DOMAIN VARCHAR2(20 BYTE),
ID_DEVICE VARCHAR2(10 BYTE),
PLANT_ID NUMBER(3)
);