CREATE TABLE T_PLC_COMPRESSION_INFO(
SCALING_FACTOR NUMBER(12,4),
COMPRESSION_TYPE VARCHAR2(3 BYTE),
NO_OF_VALID_5MIN NUMBER(22,3),
NO_OF_VALID_HOUR NUMBER(22,3),
NO_OF_VALID_SHIFT NUMBER(22,3),
NO_OF_VALID_DAY NUMBER(22,3),
COMPRESSION_ID NUMBER(2) UNIQUE
);