CREATE TABLE T_PLC_PERIODIC_DATA_LOG(
ID_PLC_DATA_SEQ1 NUMBER(6) NOT NULL,
DATA_RECEIVED_MOMENT2 DATE NOT NULL,
ACT_COMPRESS_UNIT  VARCHAR2(1 BYTE),
VALUE NUMBER(16,8),
WARNING_STATUS  VARCHAR2(10 BYTE),
ERR_STATUS VARCHAR2(10 BYTE)
);