CREATE TABLE T_PLC_TAG_CONFIG(
ID_PLC_DATA_SEQ NUMBER(6) NOT NULL,
ID_APP_TAG VARCHAR2(50 BYTE) NOT NULL,
ID_SOURCE VARCHAR2(10 BYTE) NOT NULL,
ID_DESTINATION VARCHAR2(10 BYTE) NOT NULL,
CD_TAG_TYPE VARCHAR2(5 BYTE) NOT NULL,
DESCRIPTION VARCHAR2(150 BYTE) NOT NULL ,
ID_PLC_TAG VARCHAR2(75 BYTE) NOT NULL,
ID_OPC NUMBER NOT NULL
);